### ISSUE TITLE
Bug Wagenreihung: Darstellung auf mobilen Geräten

### ISSUE THREAD

**Issue by EinfachRuwen** [hoolycrash/trainboard#10]
Train:2075 Datetime:202404271751 Station:8002549

Die Darstellung auf Smartphones ist weiterhin ein wenig seltsam.![image](https://github.com/hoolycrash/trainboard/assets/76685126/7bd22ac2-0c71-474e-839e-77c6aff7e8f4)

**Comment by hoolycrash** [comment]
Schon einmal Browser Cache gelöscht? Das dürfte das Problem lösen.
