### ISSUE TITLE
The display of individual trains is no longer possible since the new tripID.

### ISSUE THREAD

**Issue by NxrVincent** [hoolycrash/trainboard#18]
![image](https://github.com/hoolycrash/trainboard/assets/29250096/f7a77f14-2553-45f4-98ff-70003ec81ca8)

**Comment by hoolycrash** [comment]
Ehm what the actual fuck. Going to figure that out soon.

**Comment by DasShorty** [comment]
Die ID kann nicht richtig aus den Query Params gelesen werden. Ebenfalls kann die API, die die Zugdaten herausgibt, den Parameter maybe auch nicht richtig "verstehen".
