### ISSUE TITLE
Gleiswechseländerung oder Ausfall

### ISSUE THREAD

**Issue by NurKai3** [hoolycrash/trainboard#26]
Gleiswechsel:
Sofern ein Gleiswechsel festgelegt wird, wird das alte Gleis nicht mehr angezeigt. Es steht nur "null" dort und dahinter das neue Gleis. 
![image](https://github.com/user-attachments/assets/a260f143-fc8f-42b1-8940-c834d1946b8f)

Ausfall:
Wenn ein Ausfall besteht, dann steht dort "null" durchgestrichen 
![image](https://github.com/user-attachments/assets/b09f0f68-6842-4e0b-8736-48a656b5db03)

Beispiel unter:
Abfahrt, Station: Karlsruhe Hbf, Gleiswechsel
Nahverkehr: Karlsruhe Neureuter Straße
Brave: Version 1.67.123 Chromium: 126.0.6478.126 (Offizieller Build)  (64-Bit)
Windows 11 23H2 x64

**Comment by DasShorty** [comment]
Schaue ich mir gleich an
