### ISSUE TITLE
x-Achse aktualisiert sich nicht wenn anderer Zeitrahmen ausgewählt wird.

### ISSUE THREAD

**Issue by Ein-Tim** [hoolycrash/trainboard#55]
Die x-Achse der Statistiken aktualisiert sich nicht, wenn man statt den standardmäßigen 30 z.B. 365 Tage auswählt.

![image](https://github.com/user-attachments/assets/08387b8a-b8c7-4bbf-8c4e-26adb667ccab)

**Comment by hoolycrash** [comment]
This is because data is only available as of 24th October 2024 (when we started collecting it).

The feature is highly experimental so it's a little roughly coded. The larger options should probably be disabled or a info message should pop up.

**Comment by hoolycrash** [comment]
Disclaimer for limited Data availability is added.
